language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
install:
  - npm install --no-optional
script:
  - npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: "71ee8424e2660dbc7dd88d81e0715f4434453db7fb57af35604d165d2db6203a"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./specs/coverage/lcov.info
