language: node_js
cache: yarn
node_js:
  - '8'
branches:
  only:
    - 'master'
jobs:
  include:
    - stage: check
      script: yarn lint
    - script: yarn flow
    - script: yarn test --coverage
      after_success:
        - yarn codecov
    - stage: build
      script: yarn babel
    - script: yarn webpack
    - stage: run
      script: yarn start-stop
    - script: yarn test-e2e
      services:
        - mongodb
      before_script:
        - mongo briskhome --eval 'db.createUser({user:"briskhome",pwd:"briskhome",roles:["readWrite"]});'
        - mongo briskhome --eval 'db.users.insert({username:"jdoe","lastName":"Doe","firstName":"John","password":"$2a$10$MTrhrVPe.8aib7b3nI2P3uoG7eDtQaWqTY5CLE3O5A9Z05bsIII0C","type":"regular","isDisabled":false,"subscriptions":[],"devices":[],"contacts":[],"__v":0});'
        - yarn babel
        - yarn webpack
        - yarn start &
        - sleep 3
addons:
  code_climate:
    repo_token: 71ee8424e2660dbc7dd88d81e0715f4434453db7fb57af35604d165d2db6203a
notifications:
  slack:
    secure: QUGo52dH4An+DP+MP1S7adoj+KGfNUxvjCS3/wfT7OVT8QPe70R98DpoGLhRt73SFlg5enYvWitz9tdzj6HA2QP3tXkL0MWlKOTg2lblZ3cJxHAqy+NcayinhjHoKDvhQwtQZ+Eo3pspneEj9emWA9HAQuJLWBw8KaGn+xRTzeker9ae88zjO19uzhBMAXQaVAYIMMShiGsWoIO5mouVk4axsR5UtR/MJiAQ7hG+Lx0/PYQBDvVFo1vsswYLz32cedPZ+XpHXyYte8TcL9EDfPeiz1N0bLMa3Z2maKZDYrIL5MLvbwZ+U7vLFiKsbUjAmGuBUmAN/uzbyzSCymcyoV0ELbZpD2/KlnBcFWb82OCkYoDW6ca6aEQhEEKMFu7ACPf51tjIbNj7q3Gu3193V2GblSR5eKVRskHg7gqla+92BHVigI5RIq4uNQOl44PupCC3rdAxCv0ohCJNgaqIcuxXJjqXTjyfkaT7Q/DEZkdAQwRvnb8eA/oiuTrYU5Hlguk1ZFO0enGJluuTu25Pg/uCJ3pr4YBXEWDDqON1JBt3RNUielOy/kyTAXPHMxLb+Ue5VB6vGUvKOBlBxuhCfUCj7Xtybd5jhmwpnqEiLv/mPobzQMneXAxAQn9ZeQdGbwc4CvhUeldsVCp/dSfKOqoheamblNC7OtaqQJ+7M+E=
