version: '3'
services: 
  core:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    command: mongod
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    logging:
#      driver: none


