// flow-typed signature: 5b5c4f09da63a5dfe05b170a2dc1e15b
// flow-typed version: <<STUB>>/agenda_v^0.8.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'agenda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'agenda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'agenda/lib/agenda' {
  declare module.exports: any;
}

declare module 'agenda/lib/job' {
  declare module.exports: any;
}

declare module 'agenda/test/agenda' {
  declare module.exports: any;
}

declare module 'agenda/test/fixtures/addTests' {
  declare module.exports: any;
}

declare module 'agenda/test/fixtures/agenda-instance' {
  declare module.exports: any;
}

// Filename aliases
declare module 'agenda/index' {
  declare module.exports: $Exports<'agenda'>;
}
declare module 'agenda/index.js' {
  declare module.exports: $Exports<'agenda'>;
}
declare module 'agenda/lib/agenda.js' {
  declare module.exports: $Exports<'agenda/lib/agenda'>;
}
declare module 'agenda/lib/job.js' {
  declare module.exports: $Exports<'agenda/lib/job'>;
}
declare module 'agenda/test/agenda.js' {
  declare module.exports: $Exports<'agenda/test/agenda'>;
}
declare module 'agenda/test/fixtures/addTests.js' {
  declare module.exports: $Exports<'agenda/test/fixtures/addTests'>;
}
declare module 'agenda/test/fixtures/agenda-instance.js' {
  declare module.exports: $Exports<'agenda/test/fixtures/agenda-instance'>;
}
