// flow-typed signature: 40fa450ad34032da85788cecfa207cf0
// flow-typed version: <<STUB>>/architect_v0.1.11/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'architect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'architect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'architect/architect' {
  declare module.exports: any;
}

declare module 'architect/plugins/architect.log/log-service' {
  declare module.exports: any;
}

// Filename aliases
declare module 'architect/architect.js' {
  declare module.exports: $Exports<'architect/architect'>;
}
declare module 'architect/plugins/architect.log/log-service.js' {
  declare module.exports: $Exports<'architect/plugins/architect.log/log-service'>;
}
