// flow-typed signature: f4debab3851d4dd29c8c7ec147ac4654
// flow-typed version: <<STUB>>/bunyan-mongodb-stream_v0.0.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bunyan-mongodb-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bunyan-mongodb-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bunyan-mongodb-stream/lib/logStream' {
  declare module.exports: any;
}

declare module 'bunyan-mongodb-stream/tests/LogStreamTests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bunyan-mongodb-stream/index' {
  declare module.exports: $Exports<'bunyan-mongodb-stream'>;
}
declare module 'bunyan-mongodb-stream/index.js' {
  declare module.exports: $Exports<'bunyan-mongodb-stream'>;
}
declare module 'bunyan-mongodb-stream/lib/logStream.js' {
  declare module.exports: $Exports<'bunyan-mongodb-stream/lib/logStream'>;
}
declare module 'bunyan-mongodb-stream/tests/LogStreamTests.js' {
  declare module.exports: $Exports<'bunyan-mongodb-stream/tests/LogStreamTests'>;
}
