// flow-typed signature: 3e276e1dd881f5f0263a68b8c7269e2e
// flow-typed version: <<STUB>>/eventemitter2_v^4.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eventemitter2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eventemitter2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eventemitter2/lib/eventemitter2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eventemitter2/index' {
  declare module.exports: $Exports<'eventemitter2'>;
}
declare module 'eventemitter2/index.js' {
  declare module.exports: $Exports<'eventemitter2'>;
}
declare module 'eventemitter2/lib/eventemitter2.js' {
  declare module.exports: $Exports<'eventemitter2/lib/eventemitter2'>;
}
