// flow-typed signature: 67211e4a98a8ef4c3b4a1f0e41dd25de
// flow-typed version: <<STUB>>/forge_v2.3.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'forge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'forge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'forge/forge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'forge/forge.js' {
  declare module.exports: $Exports<'forge/forge'>;
}
