// flow-typed signature: 1d7b1bfe0f02d4e5718cfd94892bf966
// flow-typed version: <<STUB>>/graphql-modules_v^0.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-modules/lib/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-modules/index' {
  declare module.exports: $Exports<'graphql-modules'>;
}
declare module 'graphql-modules/index.js' {
  declare module.exports: $Exports<'graphql-modules'>;
}
declare module 'graphql-modules/lib/bundle.js' {
  declare module.exports: $Exports<'graphql-modules/lib/bundle'>;
}
