// flow-typed signature: b77fb2e52e86337d96712fb6bc1aeab2
// flow-typed version: <<STUB>>/kerberos_v0.0.19/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kerberos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kerberos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kerberos/lib/auth_processes/mongodb' {
  declare module.exports: any;
}

declare module 'kerberos/lib/kerberos' {
  declare module.exports: any;
}

declare module 'kerberos/lib/sspi' {
  declare module.exports: any;
}

declare module 'kerberos/lib/win32/wrappers/security_buffer_descriptor' {
  declare module.exports: any;
}

declare module 'kerberos/lib/win32/wrappers/security_buffer' {
  declare module.exports: any;
}

declare module 'kerberos/lib/win32/wrappers/security_context' {
  declare module.exports: any;
}

declare module 'kerberos/lib/win32/wrappers/security_credentials' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kerberos/index' {
  declare module.exports: $Exports<'kerberos'>;
}
declare module 'kerberos/index.js' {
  declare module.exports: $Exports<'kerberos'>;
}
declare module 'kerberos/lib/auth_processes/mongodb.js' {
  declare module.exports: $Exports<'kerberos/lib/auth_processes/mongodb'>;
}
declare module 'kerberos/lib/kerberos.js' {
  declare module.exports: $Exports<'kerberos/lib/kerberos'>;
}
declare module 'kerberos/lib/sspi.js' {
  declare module.exports: $Exports<'kerberos/lib/sspi'>;
}
declare module 'kerberos/lib/win32/wrappers/security_buffer_descriptor.js' {
  declare module.exports: $Exports<'kerberos/lib/win32/wrappers/security_buffer_descriptor'>;
}
declare module 'kerberos/lib/win32/wrappers/security_buffer.js' {
  declare module.exports: $Exports<'kerberos/lib/win32/wrappers/security_buffer'>;
}
declare module 'kerberos/lib/win32/wrappers/security_context.js' {
  declare module.exports: $Exports<'kerberos/lib/win32/wrappers/security_context'>;
}
declare module 'kerberos/lib/win32/wrappers/security_credentials.js' {
  declare module.exports: $Exports<'kerberos/lib/win32/wrappers/security_credentials'>;
}
