// flow-typed signature: b673ea85f170fd3b4e598781338cfae5
// flow-typed version: <<STUB>>/ldapjs_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ldapjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ldapjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ldapjs/lib/assert' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/attribute' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/change' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/client/client' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/client/index' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/client/search_pager' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/control' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/entry_change_notification_control' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/index' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/paged_results_control' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/persistent_search_control' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/server_side_sorting_request_control' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/controls/server_side_sorting_response_control' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/dn' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/dtrace' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/errors/codes' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/errors/index' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/and_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/approx_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/equality_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/escape' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/ext_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/ge_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/index' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/le_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/not_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/or_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/presence_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/filters/substr_filter' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/index' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/abandon_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/abandon_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/add_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/add_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/bind_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/bind_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/compare_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/compare_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/del_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/del_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/ext_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/ext_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/index' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/message' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/moddn_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/moddn_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/modify_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/modify_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/parser' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/result' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/search_entry' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/search_reference' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/search_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/search_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/unbind_request' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/messages/unbind_response' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/persistent_search' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/protocol' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/server' {
  declare module.exports: any;
}

declare module 'ldapjs/lib/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ldapjs/lib/assert.js' {
  declare module.exports: $Exports<'ldapjs/lib/assert'>;
}
declare module 'ldapjs/lib/attribute.js' {
  declare module.exports: $Exports<'ldapjs/lib/attribute'>;
}
declare module 'ldapjs/lib/change.js' {
  declare module.exports: $Exports<'ldapjs/lib/change'>;
}
declare module 'ldapjs/lib/client/client.js' {
  declare module.exports: $Exports<'ldapjs/lib/client/client'>;
}
declare module 'ldapjs/lib/client/index.js' {
  declare module.exports: $Exports<'ldapjs/lib/client/index'>;
}
declare module 'ldapjs/lib/client/search_pager.js' {
  declare module.exports: $Exports<'ldapjs/lib/client/search_pager'>;
}
declare module 'ldapjs/lib/controls/control.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/control'>;
}
declare module 'ldapjs/lib/controls/entry_change_notification_control.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/entry_change_notification_control'>;
}
declare module 'ldapjs/lib/controls/index.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/index'>;
}
declare module 'ldapjs/lib/controls/paged_results_control.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/paged_results_control'>;
}
declare module 'ldapjs/lib/controls/persistent_search_control.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/persistent_search_control'>;
}
declare module 'ldapjs/lib/controls/server_side_sorting_request_control.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/server_side_sorting_request_control'>;
}
declare module 'ldapjs/lib/controls/server_side_sorting_response_control.js' {
  declare module.exports: $Exports<'ldapjs/lib/controls/server_side_sorting_response_control'>;
}
declare module 'ldapjs/lib/dn.js' {
  declare module.exports: $Exports<'ldapjs/lib/dn'>;
}
declare module 'ldapjs/lib/dtrace.js' {
  declare module.exports: $Exports<'ldapjs/lib/dtrace'>;
}
declare module 'ldapjs/lib/errors/codes.js' {
  declare module.exports: $Exports<'ldapjs/lib/errors/codes'>;
}
declare module 'ldapjs/lib/errors/index.js' {
  declare module.exports: $Exports<'ldapjs/lib/errors/index'>;
}
declare module 'ldapjs/lib/filters/and_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/and_filter'>;
}
declare module 'ldapjs/lib/filters/approx_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/approx_filter'>;
}
declare module 'ldapjs/lib/filters/equality_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/equality_filter'>;
}
declare module 'ldapjs/lib/filters/escape.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/escape'>;
}
declare module 'ldapjs/lib/filters/ext_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/ext_filter'>;
}
declare module 'ldapjs/lib/filters/filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/filter'>;
}
declare module 'ldapjs/lib/filters/ge_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/ge_filter'>;
}
declare module 'ldapjs/lib/filters/index.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/index'>;
}
declare module 'ldapjs/lib/filters/le_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/le_filter'>;
}
declare module 'ldapjs/lib/filters/not_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/not_filter'>;
}
declare module 'ldapjs/lib/filters/or_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/or_filter'>;
}
declare module 'ldapjs/lib/filters/presence_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/presence_filter'>;
}
declare module 'ldapjs/lib/filters/substr_filter.js' {
  declare module.exports: $Exports<'ldapjs/lib/filters/substr_filter'>;
}
declare module 'ldapjs/lib/index.js' {
  declare module.exports: $Exports<'ldapjs/lib/index'>;
}
declare module 'ldapjs/lib/messages/abandon_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/abandon_request'>;
}
declare module 'ldapjs/lib/messages/abandon_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/abandon_response'>;
}
declare module 'ldapjs/lib/messages/add_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/add_request'>;
}
declare module 'ldapjs/lib/messages/add_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/add_response'>;
}
declare module 'ldapjs/lib/messages/bind_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/bind_request'>;
}
declare module 'ldapjs/lib/messages/bind_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/bind_response'>;
}
declare module 'ldapjs/lib/messages/compare_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/compare_request'>;
}
declare module 'ldapjs/lib/messages/compare_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/compare_response'>;
}
declare module 'ldapjs/lib/messages/del_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/del_request'>;
}
declare module 'ldapjs/lib/messages/del_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/del_response'>;
}
declare module 'ldapjs/lib/messages/ext_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/ext_request'>;
}
declare module 'ldapjs/lib/messages/ext_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/ext_response'>;
}
declare module 'ldapjs/lib/messages/index.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/index'>;
}
declare module 'ldapjs/lib/messages/message.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/message'>;
}
declare module 'ldapjs/lib/messages/moddn_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/moddn_request'>;
}
declare module 'ldapjs/lib/messages/moddn_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/moddn_response'>;
}
declare module 'ldapjs/lib/messages/modify_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/modify_request'>;
}
declare module 'ldapjs/lib/messages/modify_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/modify_response'>;
}
declare module 'ldapjs/lib/messages/parser.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/parser'>;
}
declare module 'ldapjs/lib/messages/result.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/result'>;
}
declare module 'ldapjs/lib/messages/search_entry.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/search_entry'>;
}
declare module 'ldapjs/lib/messages/search_reference.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/search_reference'>;
}
declare module 'ldapjs/lib/messages/search_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/search_request'>;
}
declare module 'ldapjs/lib/messages/search_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/search_response'>;
}
declare module 'ldapjs/lib/messages/unbind_request.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/unbind_request'>;
}
declare module 'ldapjs/lib/messages/unbind_response.js' {
  declare module.exports: $Exports<'ldapjs/lib/messages/unbind_response'>;
}
declare module 'ldapjs/lib/persistent_search.js' {
  declare module.exports: $Exports<'ldapjs/lib/persistent_search'>;
}
declare module 'ldapjs/lib/protocol.js' {
  declare module.exports: $Exports<'ldapjs/lib/protocol'>;
}
declare module 'ldapjs/lib/server.js' {
  declare module.exports: $Exports<'ldapjs/lib/server'>;
}
declare module 'ldapjs/lib/url.js' {
  declare module.exports: $Exports<'ldapjs/lib/url'>;
}
