// flow-typed signature: dd2041b039bdb7fc33547fe8d5fb5a78
// flow-typed version: <<STUB>>/mjpeg-proxy_v^0.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mjpeg-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mjpeg-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mjpeg-proxy/mjpeg-proxy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mjpeg-proxy/mjpeg-proxy.js' {
  declare module.exports: $Exports<'mjpeg-proxy/mjpeg-proxy'>;
}
