// flow-typed signature: 742cf0edcb2772c186b79560a9d27ded
// flow-typed version: <<STUB>>/mock-dgram_v0.1.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-dgram'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-dgram' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-dgram/dgram' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-dgram/dgram.js' {
  declare module.exports: $Exports<'mock-dgram/dgram'>;
}
