// flow-typed signature: e7657df663c88659d3f358660ce2a749
// flow-typed version: <<STUB>>/mockgoose_v^6.0.8/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockgoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockgoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockgoose/Mockgoose' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockgoose/Mockgoose.js' {
  declare module.exports: $Exports<'mockgoose/Mockgoose'>;
}
