// flow-typed signature: 383bf05f762d7e10afe7d4e24970fbd7
// flow-typed version: <<STUB>>/mongoose_v4.2.8/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose' {
  declare interface Mongoose {
    model(id: string): Mongoose$Model<*>,
  }

  declare export class Mongoose$Model<?T> {
    constructor(T): T,

    static find(obj: Object): Promise<typeof T[]>,
    static findOne(obj: Object): Promise<typeof T>,
  }

  declare export default Mongoose
}
