// flow-typed signature: e359d90fd41c18d15821ff9d28a8d30e
// flow-typed version: <<STUB>>/mongo-mock_v2.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongo-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongo-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongo-mock/lib/collection' {
  declare module.exports: any;
}

declare module 'mongo-mock/lib/cursor' {
  declare module.exports: any;
}

declare module 'mongo-mock/lib/db' {
  declare module.exports: any;
}

declare module 'mongo-mock/lib/mongo_client' {
  declare module.exports: any;
}

declare module 'mongo-mock/mongo-mock' {
  declare module.exports: any;
}

declare module 'mongo-mock/sift' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongo-mock/lib/collection.js' {
  declare module.exports: $Exports<'mongo-mock/lib/collection'>;
}
declare module 'mongo-mock/lib/cursor.js' {
  declare module.exports: $Exports<'mongo-mock/lib/cursor'>;
}
declare module 'mongo-mock/lib/db.js' {
  declare module.exports: $Exports<'mongo-mock/lib/db'>;
}
declare module 'mongo-mock/lib/mongo_client.js' {
  declare module.exports: $Exports<'mongo-mock/lib/mongo_client'>;
}
declare module 'mongo-mock/mongo-mock.js' {
  declare module.exports: $Exports<'mongo-mock/mongo-mock'>;
}
declare module 'mongo-mock/sift.js' {
  declare module.exports: $Exports<'mongo-mock/sift'>;
}
