// flow-typed signature: cc2daa0edcffbda31c1b4af01a7c225c
// flow-typed version: <<STUB>>/mosca_v2.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mosca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mosca' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mosca/lib/authorizer' {
  declare module.exports: any;
}

declare module 'mosca/lib/cli' {
  declare module.exports: any;
}

declare module 'mosca/lib/client' {
  declare module.exports: any;
}

declare module 'mosca/lib/interfaces' {
  declare module.exports: any;
}

declare module 'mosca/lib/options' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/abstract' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/index' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/levelup' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/matcher' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/memory' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/mongo' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/redis' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/utils' {
  declare module.exports: any;
}

declare module 'mosca/lib/serializers' {
  declare module.exports: any;
}

declare module 'mosca/lib/server' {
  declare module.exports: any;
}

declare module 'mosca/lib/stats' {
  declare module.exports: any;
}

declare module 'mosca/public/mqtt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mosca/index' {
  declare module.exports: $Exports<'mosca'>;
}
declare module 'mosca/index.js' {
  declare module.exports: $Exports<'mosca'>;
}
declare module 'mosca/lib/authorizer.js' {
  declare module.exports: $Exports<'mosca/lib/authorizer'>;
}
declare module 'mosca/lib/cli.js' {
  declare module.exports: $Exports<'mosca/lib/cli'>;
}
declare module 'mosca/lib/client.js' {
  declare module.exports: $Exports<'mosca/lib/client'>;
}
declare module 'mosca/lib/interfaces.js' {
  declare module.exports: $Exports<'mosca/lib/interfaces'>;
}
declare module 'mosca/lib/options.js' {
  declare module.exports: $Exports<'mosca/lib/options'>;
}
declare module 'mosca/lib/persistence/abstract.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/abstract'>;
}
declare module 'mosca/lib/persistence/index.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/index'>;
}
declare module 'mosca/lib/persistence/levelup.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/levelup'>;
}
declare module 'mosca/lib/persistence/matcher.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/matcher'>;
}
declare module 'mosca/lib/persistence/memory.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/memory'>;
}
declare module 'mosca/lib/persistence/mongo.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/mongo'>;
}
declare module 'mosca/lib/persistence/redis.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/redis'>;
}
declare module 'mosca/lib/persistence/utils.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/utils'>;
}
declare module 'mosca/lib/serializers.js' {
  declare module.exports: $Exports<'mosca/lib/serializers'>;
}
declare module 'mosca/lib/server.js' {
  declare module.exports: $Exports<'mosca/lib/server'>;
}
declare module 'mosca/lib/stats.js' {
  declare module.exports: $Exports<'mosca/lib/stats'>;
}
declare module 'mosca/public/mqtt.js' {
  declare module.exports: $Exports<'mosca/public/mqtt'>;
}
