// flow-typed signature: ee7a29c9f9fc54c7d2c29fb775ad1073
// flow-typed version: <<STUB>>/nconf_v^0.8.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nconf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nconf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nconf/lib/nconf' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/common' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/formats' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/provider' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/stores/argv' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/stores/env' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/stores/file' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/stores/literal' {
  declare module.exports: any;
}

declare module 'nconf/lib/nconf/stores/memory' {
  declare module.exports: any;
}

declare module 'nconf/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nconf/lib/nconf.js' {
  declare module.exports: $Exports<'nconf/lib/nconf'>;
}
declare module 'nconf/lib/nconf/common.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/common'>;
}
declare module 'nconf/lib/nconf/formats.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/formats'>;
}
declare module 'nconf/lib/nconf/provider.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/provider'>;
}
declare module 'nconf/lib/nconf/stores/argv.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/stores/argv'>;
}
declare module 'nconf/lib/nconf/stores/env.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/stores/env'>;
}
declare module 'nconf/lib/nconf/stores/file.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/stores/file'>;
}
declare module 'nconf/lib/nconf/stores/literal.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/stores/literal'>;
}
declare module 'nconf/lib/nconf/stores/memory.js' {
  declare module.exports: $Exports<'nconf/lib/nconf/stores/memory'>;
}
declare module 'nconf/usage.js' {
  declare module.exports: $Exports<'nconf/usage'>;
}
