// flow-typed signature: 825b3a4acc0c59555396b8668d916037
// flow-typed version: <<STUB>>/node-persist_v0.0.11/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-persist/src/local-storage' {
  declare module.exports: any;
}

declare module 'node-persist/src/node-persist' {
  declare module.exports: any;
}

declare module 'node-persist/temp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-persist/src/local-storage.js' {
  declare module.exports: $Exports<'node-persist/src/local-storage'>;
}
declare module 'node-persist/src/node-persist.js' {
  declare module.exports: $Exports<'node-persist/src/node-persist'>;
}
declare module 'node-persist/temp.js' {
  declare module.exports: $Exports<'node-persist/temp'>;
}
