// flow-typed signature: a346ac63ff8d53937adec56a415c61d5
// flow-typed version: <<STUB>>/node-nut_v^0.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-nut'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-nut' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-nut/node-nut' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-nut/node-nut.js' {
  declare module.exports: $Exports<'node-nut/node-nut'>;
}
