// flow-typed signature: dfafe696dde168bdcdfe3834867e689a
// flow-typed version: <<STUB>>/node-forge_v^0.6.48/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-forge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-forge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-forge/js/aes' {
  declare module.exports: any;
}

declare module 'node-forge/js/aesCipherSuites' {
  declare module.exports: any;
}

declare module 'node-forge/js/asn1' {
  declare module.exports: any;
}

declare module 'node-forge/js/cipher' {
  declare module.exports: any;
}

declare module 'node-forge/js/cipherModes' {
  declare module.exports: any;
}

declare module 'node-forge/js/debug' {
  declare module.exports: any;
}

declare module 'node-forge/js/des' {
  declare module.exports: any;
}

declare module 'node-forge/js/forge' {
  declare module.exports: any;
}

declare module 'node-forge/js/form' {
  declare module.exports: any;
}

declare module 'node-forge/js/hmac' {
  declare module.exports: any;
}

declare module 'node-forge/js/http' {
  declare module.exports: any;
}

declare module 'node-forge/js/jsbn' {
  declare module.exports: any;
}

declare module 'node-forge/js/kem' {
  declare module.exports: any;
}

declare module 'node-forge/js/log' {
  declare module.exports: any;
}

declare module 'node-forge/js/md' {
  declare module.exports: any;
}

declare module 'node-forge/js/md5' {
  declare module.exports: any;
}

declare module 'node-forge/js/mgf' {
  declare module.exports: any;
}

declare module 'node-forge/js/mgf1' {
  declare module.exports: any;
}

declare module 'node-forge/js/oids' {
  declare module.exports: any;
}

declare module 'node-forge/js/pbe' {
  declare module.exports: any;
}

declare module 'node-forge/js/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-forge/js/pem' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs1' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs12' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs7' {
  declare module.exports: any;
}

declare module 'node-forge/js/pkcs7asn1' {
  declare module.exports: any;
}

declare module 'node-forge/js/pki' {
  declare module.exports: any;
}

declare module 'node-forge/js/prime' {
  declare module.exports: any;
}

declare module 'node-forge/js/prime.worker' {
  declare module.exports: any;
}

declare module 'node-forge/js/prng' {
  declare module.exports: any;
}

declare module 'node-forge/js/pss' {
  declare module.exports: any;
}

declare module 'node-forge/js/random' {
  declare module.exports: any;
}

declare module 'node-forge/js/rc2' {
  declare module.exports: any;
}

declare module 'node-forge/js/rsa' {
  declare module.exports: any;
}

declare module 'node-forge/js/sha1' {
  declare module.exports: any;
}

declare module 'node-forge/js/sha256' {
  declare module.exports: any;
}

declare module 'node-forge/js/sha512' {
  declare module.exports: any;
}

declare module 'node-forge/js/socket' {
  declare module.exports: any;
}

declare module 'node-forge/js/ssh' {
  declare module.exports: any;
}

declare module 'node-forge/js/task' {
  declare module.exports: any;
}

declare module 'node-forge/js/tls' {
  declare module.exports: any;
}

declare module 'node-forge/js/tlssocket' {
  declare module.exports: any;
}

declare module 'node-forge/js/util' {
  declare module.exports: any;
}

declare module 'node-forge/js/x509' {
  declare module.exports: any;
}

declare module 'node-forge/js/xhr' {
  declare module.exports: any;
}

declare module 'node-forge/minify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-forge/js/aes.js' {
  declare module.exports: $Exports<'node-forge/js/aes'>;
}
declare module 'node-forge/js/aesCipherSuites.js' {
  declare module.exports: $Exports<'node-forge/js/aesCipherSuites'>;
}
declare module 'node-forge/js/asn1.js' {
  declare module.exports: $Exports<'node-forge/js/asn1'>;
}
declare module 'node-forge/js/cipher.js' {
  declare module.exports: $Exports<'node-forge/js/cipher'>;
}
declare module 'node-forge/js/cipherModes.js' {
  declare module.exports: $Exports<'node-forge/js/cipherModes'>;
}
declare module 'node-forge/js/debug.js' {
  declare module.exports: $Exports<'node-forge/js/debug'>;
}
declare module 'node-forge/js/des.js' {
  declare module.exports: $Exports<'node-forge/js/des'>;
}
declare module 'node-forge/js/forge.js' {
  declare module.exports: $Exports<'node-forge/js/forge'>;
}
declare module 'node-forge/js/form.js' {
  declare module.exports: $Exports<'node-forge/js/form'>;
}
declare module 'node-forge/js/hmac.js' {
  declare module.exports: $Exports<'node-forge/js/hmac'>;
}
declare module 'node-forge/js/http.js' {
  declare module.exports: $Exports<'node-forge/js/http'>;
}
declare module 'node-forge/js/jsbn.js' {
  declare module.exports: $Exports<'node-forge/js/jsbn'>;
}
declare module 'node-forge/js/kem.js' {
  declare module.exports: $Exports<'node-forge/js/kem'>;
}
declare module 'node-forge/js/log.js' {
  declare module.exports: $Exports<'node-forge/js/log'>;
}
declare module 'node-forge/js/md.js' {
  declare module.exports: $Exports<'node-forge/js/md'>;
}
declare module 'node-forge/js/md5.js' {
  declare module.exports: $Exports<'node-forge/js/md5'>;
}
declare module 'node-forge/js/mgf.js' {
  declare module.exports: $Exports<'node-forge/js/mgf'>;
}
declare module 'node-forge/js/mgf1.js' {
  declare module.exports: $Exports<'node-forge/js/mgf1'>;
}
declare module 'node-forge/js/oids.js' {
  declare module.exports: $Exports<'node-forge/js/oids'>;
}
declare module 'node-forge/js/pbe.js' {
  declare module.exports: $Exports<'node-forge/js/pbe'>;
}
declare module 'node-forge/js/pbkdf2.js' {
  declare module.exports: $Exports<'node-forge/js/pbkdf2'>;
}
declare module 'node-forge/js/pem.js' {
  declare module.exports: $Exports<'node-forge/js/pem'>;
}
declare module 'node-forge/js/pkcs1.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs1'>;
}
declare module 'node-forge/js/pkcs12.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs12'>;
}
declare module 'node-forge/js/pkcs7.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs7'>;
}
declare module 'node-forge/js/pkcs7asn1.js' {
  declare module.exports: $Exports<'node-forge/js/pkcs7asn1'>;
}
declare module 'node-forge/js/pki.js' {
  declare module.exports: $Exports<'node-forge/js/pki'>;
}
declare module 'node-forge/js/prime.js' {
  declare module.exports: $Exports<'node-forge/js/prime'>;
}
declare module 'node-forge/js/prime.worker.js' {
  declare module.exports: $Exports<'node-forge/js/prime.worker'>;
}
declare module 'node-forge/js/prng.js' {
  declare module.exports: $Exports<'node-forge/js/prng'>;
}
declare module 'node-forge/js/pss.js' {
  declare module.exports: $Exports<'node-forge/js/pss'>;
}
declare module 'node-forge/js/random.js' {
  declare module.exports: $Exports<'node-forge/js/random'>;
}
declare module 'node-forge/js/rc2.js' {
  declare module.exports: $Exports<'node-forge/js/rc2'>;
}
declare module 'node-forge/js/rsa.js' {
  declare module.exports: $Exports<'node-forge/js/rsa'>;
}
declare module 'node-forge/js/sha1.js' {
  declare module.exports: $Exports<'node-forge/js/sha1'>;
}
declare module 'node-forge/js/sha256.js' {
  declare module.exports: $Exports<'node-forge/js/sha256'>;
}
declare module 'node-forge/js/sha512.js' {
  declare module.exports: $Exports<'node-forge/js/sha512'>;
}
declare module 'node-forge/js/socket.js' {
  declare module.exports: $Exports<'node-forge/js/socket'>;
}
declare module 'node-forge/js/ssh.js' {
  declare module.exports: $Exports<'node-forge/js/ssh'>;
}
declare module 'node-forge/js/task.js' {
  declare module.exports: $Exports<'node-forge/js/task'>;
}
declare module 'node-forge/js/tls.js' {
  declare module.exports: $Exports<'node-forge/js/tls'>;
}
declare module 'node-forge/js/tlssocket.js' {
  declare module.exports: $Exports<'node-forge/js/tlssocket'>;
}
declare module 'node-forge/js/util.js' {
  declare module.exports: $Exports<'node-forge/js/util'>;
}
declare module 'node-forge/js/x509.js' {
  declare module.exports: $Exports<'node-forge/js/x509'>;
}
declare module 'node-forge/js/xhr.js' {
  declare module.exports: $Exports<'node-forge/js/xhr'>;
}
declare module 'node-forge/minify.js' {
  declare module.exports: $Exports<'node-forge/minify'>;
}
