// flow-typed signature: 6d3574cb7c955a702f0d3fe20bf03f11
// flow-typed version: <<STUB>>/node-telegram-bot-api_v^0.21.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-telegram-bot-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-telegram-bot-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-telegram-bot-api/examples/httpsWebHook' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/examples/openShiftWebHook' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/examples/polling' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/examples/replyToMessage' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/src/telegram' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/src/telegramPolling' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/src/telegramWebHook' {
  declare module.exports: any;
}

declare module 'node-telegram-bot-api/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-telegram-bot-api/examples/httpsWebHook.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/examples/httpsWebHook'>;
}
declare module 'node-telegram-bot-api/examples/openShiftWebHook.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/examples/openShiftWebHook'>;
}
declare module 'node-telegram-bot-api/examples/polling.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/examples/polling'>;
}
declare module 'node-telegram-bot-api/examples/replyToMessage.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/examples/replyToMessage'>;
}
declare module 'node-telegram-bot-api/index' {
  declare module.exports: $Exports<'node-telegram-bot-api'>;
}
declare module 'node-telegram-bot-api/index.js' {
  declare module.exports: $Exports<'node-telegram-bot-api'>;
}
declare module 'node-telegram-bot-api/src/telegram.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/src/telegram'>;
}
declare module 'node-telegram-bot-api/src/telegramPolling.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/src/telegramPolling'>;
}
declare module 'node-telegram-bot-api/src/telegramWebHook.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/src/telegramWebHook'>;
}
declare module 'node-telegram-bot-api/test/index.js' {
  declare module.exports: $Exports<'node-telegram-bot-api/test/index'>;
}
