// flow-typed signature: c885fe69fa66113b49c3a5f61de2e8aa
// flow-typed version: <<STUB>>/passport-restify_v1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-restify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-restify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-restify/lib/authenticator' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/errors/authenticationerror' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/framework/connect' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/http/request' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/index' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/middleware/authenticate' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/middleware/initialize' {
  declare module.exports: any;
}

declare module 'passport-restify/lib/strategies/session' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-restify/lib/authenticator.js' {
  declare module.exports: $Exports<'passport-restify/lib/authenticator'>;
}
declare module 'passport-restify/lib/errors/authenticationerror.js' {
  declare module.exports: $Exports<'passport-restify/lib/errors/authenticationerror'>;
}
declare module 'passport-restify/lib/framework/connect.js' {
  declare module.exports: $Exports<'passport-restify/lib/framework/connect'>;
}
declare module 'passport-restify/lib/http/request.js' {
  declare module.exports: $Exports<'passport-restify/lib/http/request'>;
}
declare module 'passport-restify/lib/index.js' {
  declare module.exports: $Exports<'passport-restify/lib/index'>;
}
declare module 'passport-restify/lib/middleware/authenticate.js' {
  declare module.exports: $Exports<'passport-restify/lib/middleware/authenticate'>;
}
declare module 'passport-restify/lib/middleware/initialize.js' {
  declare module.exports: $Exports<'passport-restify/lib/middleware/initialize'>;
}
declare module 'passport-restify/lib/strategies/session.js' {
  declare module.exports: $Exports<'passport-restify/lib/strategies/session'>;
}
