// flow-typed signature: 078d47bd4741d7688a88a6a17911d1e0
// flow-typed version: <<STUB>>/passport-localapikey-update_vgithub:heuels/passport-localapikey-restify/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-localapikey-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-localapikey-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-localapikey-update/lib/passport-localapikey/errors/badrequesterror' {
  declare module.exports: any;
}

declare module 'passport-localapikey-update/lib/passport-localapikey/index' {
  declare module.exports: any;
}

declare module 'passport-localapikey-update/lib/passport-localapikey/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-localapikey-update/lib/passport-localapikey/errors/badrequesterror.js' {
  declare module.exports: $Exports<'passport-localapikey-update/lib/passport-localapikey/errors/badrequesterror'>;
}
declare module 'passport-localapikey-update/lib/passport-localapikey/index.js' {
  declare module.exports: $Exports<'passport-localapikey-update/lib/passport-localapikey/index'>;
}
declare module 'passport-localapikey-update/lib/passport-localapikey/strategy.js' {
  declare module.exports: $Exports<'passport-localapikey-update/lib/passport-localapikey/strategy'>;
}
