// flow-typed signature: 34787c33c23d94aea59b90a0c4043481
// flow-typed version: <<STUB>>/rc-menu_v^5.0.10/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-menu/lib/Divider' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/DOMWrap' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/index' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/Menu' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/MenuItem' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/MenuItemGroup' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/MenuMixin' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/SubMenu' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/SubMenuStateMixin' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/SubPopupMenu' {
  declare module.exports: any;
}

declare module 'rc-menu/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-menu/lib/Divider.js' {
  declare module.exports: $Exports<'rc-menu/lib/Divider'>;
}
declare module 'rc-menu/lib/DOMWrap.js' {
  declare module.exports: $Exports<'rc-menu/lib/DOMWrap'>;
}
declare module 'rc-menu/lib/index.js' {
  declare module.exports: $Exports<'rc-menu/lib/index'>;
}
declare module 'rc-menu/lib/Menu.js' {
  declare module.exports: $Exports<'rc-menu/lib/Menu'>;
}
declare module 'rc-menu/lib/MenuItem.js' {
  declare module.exports: $Exports<'rc-menu/lib/MenuItem'>;
}
declare module 'rc-menu/lib/MenuItemGroup.js' {
  declare module.exports: $Exports<'rc-menu/lib/MenuItemGroup'>;
}
declare module 'rc-menu/lib/MenuMixin.js' {
  declare module.exports: $Exports<'rc-menu/lib/MenuMixin'>;
}
declare module 'rc-menu/lib/SubMenu.js' {
  declare module.exports: $Exports<'rc-menu/lib/SubMenu'>;
}
declare module 'rc-menu/lib/SubMenuStateMixin.js' {
  declare module.exports: $Exports<'rc-menu/lib/SubMenuStateMixin'>;
}
declare module 'rc-menu/lib/SubPopupMenu.js' {
  declare module.exports: $Exports<'rc-menu/lib/SubPopupMenu'>;
}
declare module 'rc-menu/lib/util.js' {
  declare module.exports: $Exports<'rc-menu/lib/util'>;
}
