// flow-typed signature: eb025aba9d7e79ca52c5eff5a42aec65
// flow-typed version: <<STUB>>/react-minimal-dropdown_v^1.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-minimal-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-minimal-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-minimal-dropdown/dist/index' {
  declare module.exports: any;
}

declare module 'react-minimal-dropdown/src/Content' {
  declare module.exports: any;
}

declare module 'react-minimal-dropdown/src/Dropdown' {
  declare module.exports: any;
}

declare module 'react-minimal-dropdown/src/Trigger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-minimal-dropdown/dist/index.js' {
  declare module.exports: $Exports<'react-minimal-dropdown/dist/index'>;
}
declare module 'react-minimal-dropdown/src/Content.js' {
  declare module.exports: $Exports<'react-minimal-dropdown/src/Content'>;
}
declare module 'react-minimal-dropdown/src/Dropdown.js' {
  declare module.exports: $Exports<'react-minimal-dropdown/src/Dropdown'>;
}
declare module 'react-minimal-dropdown/src/Trigger.js' {
  declare module.exports: $Exports<'react-minimal-dropdown/src/Trigger'>;
}
