// flow-typed signature: 807e98ede79de6c51dc498851d8da911
// flow-typed version: <<STUB>>/react-dropdown_vheuels/react-dropdown#disabled_classname/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropdown/dist/index' {
  declare module.exports: any;
}

declare module 'react-dropdown/example/flatArrayExample' {
  declare module.exports: any;
}

declare module 'react-dropdown/example/main' {
  declare module.exports: any;
}

declare module 'react-dropdown/example/objectArrayExample' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropdown/dist/index.js' {
  declare module.exports: $Exports<'react-dropdown/dist/index'>;
}
declare module 'react-dropdown/example/flatArrayExample.js' {
  declare module.exports: $Exports<'react-dropdown/example/flatArrayExample'>;
}
declare module 'react-dropdown/example/main.js' {
  declare module.exports: $Exports<'react-dropdown/example/main'>;
}
declare module 'react-dropdown/example/objectArrayExample.js' {
  declare module.exports: $Exports<'react-dropdown/example/objectArrayExample'>;
}
declare module 'react-dropdown/index' {
  declare module.exports: $Exports<'react-dropdown'>;
}
declare module 'react-dropdown/index.js' {
  declare module.exports: $Exports<'react-dropdown'>;
}
