// flow-typed signature: 4647cf86d9b6ee83a63a027dd92482ce
// flow-typed version: <<STUB>>/react-input-mask_v1.0.7/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-mask'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-mask' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-mask/dist/react-input-mask' {
  declare module.exports: any;
}

declare module 'react-input-mask/dist/react-input-mask.min' {
  declare module.exports: any;
}

declare module 'react-input-mask/es/constants/index' {
  declare module.exports: any;
}

declare module 'react-input-mask/es/index' {
  declare module.exports: any;
}

declare module 'react-input-mask/es/utils/defer' {
  declare module.exports: any;
}

declare module 'react-input-mask/es/utils/environment' {
  declare module.exports: any;
}

declare module 'react-input-mask/es/utils/parseMask' {
  declare module.exports: any;
}

declare module 'react-input-mask/es/utils/string' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/constants/index' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/index' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/utils/defer' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/utils/environment' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/utils/parseMask' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/utils/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-mask/dist/react-input-mask.js' {
  declare module.exports: $Exports<'react-input-mask/dist/react-input-mask'>;
}
declare module 'react-input-mask/dist/react-input-mask.min.js' {
  declare module.exports: $Exports<'react-input-mask/dist/react-input-mask.min'>;
}
declare module 'react-input-mask/es/constants/index.js' {
  declare module.exports: $Exports<'react-input-mask/es/constants/index'>;
}
declare module 'react-input-mask/es/index.js' {
  declare module.exports: $Exports<'react-input-mask/es/index'>;
}
declare module 'react-input-mask/es/utils/defer.js' {
  declare module.exports: $Exports<'react-input-mask/es/utils/defer'>;
}
declare module 'react-input-mask/es/utils/environment.js' {
  declare module.exports: $Exports<'react-input-mask/es/utils/environment'>;
}
declare module 'react-input-mask/es/utils/parseMask.js' {
  declare module.exports: $Exports<'react-input-mask/es/utils/parseMask'>;
}
declare module 'react-input-mask/es/utils/string.js' {
  declare module.exports: $Exports<'react-input-mask/es/utils/string'>;
}
declare module 'react-input-mask/lib/constants/index.js' {
  declare module.exports: $Exports<'react-input-mask/lib/constants/index'>;
}
declare module 'react-input-mask/lib/index.js' {
  declare module.exports: $Exports<'react-input-mask/lib/index'>;
}
declare module 'react-input-mask/lib/utils/defer.js' {
  declare module.exports: $Exports<'react-input-mask/lib/utils/defer'>;
}
declare module 'react-input-mask/lib/utils/environment.js' {
  declare module.exports: $Exports<'react-input-mask/lib/utils/environment'>;
}
declare module 'react-input-mask/lib/utils/parseMask.js' {
  declare module.exports: $Exports<'react-input-mask/lib/utils/parseMask'>;
}
declare module 'react-input-mask/lib/utils/string.js' {
  declare module.exports: $Exports<'react-input-mask/lib/utils/string'>;
}
