// flow-typed signature: 266f9cf8d92c769f9d7a1feea9330e1d
// flow-typed version: <<STUB>>/restify_v4.0.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'restify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restify/lib/bunyan_helper' {
  declare module.exports: any;
}

declare module 'restify/lib/clients/http_client' {
  declare module.exports: any;
}

declare module 'restify/lib/clients/index' {
  declare module.exports: any;
}

declare module 'restify/lib/clients/json_client' {
  declare module.exports: any;
}

declare module 'restify/lib/clients/string_client' {
  declare module.exports: any;
}

declare module 'restify/lib/dtrace' {
  declare module.exports: any;
}

declare module 'restify/lib/errors/http_error' {
  declare module.exports: any;
}

declare module 'restify/lib/errors/index' {
  declare module.exports: any;
}

declare module 'restify/lib/errors/rest_error' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/binary' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/index' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/json' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/jsonp' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/text' {
  declare module.exports: any;
}

declare module 'restify/lib/http_date' {
  declare module.exports: any;
}

declare module 'restify/lib/index' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/accept' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/audit' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/authorization' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/body_parser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/body_reader' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/bunyan' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/conditional_request' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/cors' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/date' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/fielded_text_body_parser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/form_body_parser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/full_response' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/gzip' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/json_body_parser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/jsonp' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/multipart_body_parser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/pause' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/pre_path' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/user_agent' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/query' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/request_expiry' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/static' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/throttle' {
  declare module.exports: any;
}

declare module 'restify/lib/request' {
  declare module.exports: any;
}

declare module 'restify/lib/response' {
  declare module.exports: any;
}

declare module 'restify/lib/router' {
  declare module.exports: any;
}

declare module 'restify/lib/server' {
  declare module.exports: any;
}

declare module 'restify/lib/upgrade' {
  declare module.exports: any;
}

declare module 'restify/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restify/lib/bunyan_helper.js' {
  declare module.exports: $Exports<'restify/lib/bunyan_helper'>;
}
declare module 'restify/lib/clients/http_client.js' {
  declare module.exports: $Exports<'restify/lib/clients/http_client'>;
}
declare module 'restify/lib/clients/index.js' {
  declare module.exports: $Exports<'restify/lib/clients/index'>;
}
declare module 'restify/lib/clients/json_client.js' {
  declare module.exports: $Exports<'restify/lib/clients/json_client'>;
}
declare module 'restify/lib/clients/string_client.js' {
  declare module.exports: $Exports<'restify/lib/clients/string_client'>;
}
declare module 'restify/lib/dtrace.js' {
  declare module.exports: $Exports<'restify/lib/dtrace'>;
}
declare module 'restify/lib/errors/http_error.js' {
  declare module.exports: $Exports<'restify/lib/errors/http_error'>;
}
declare module 'restify/lib/errors/index.js' {
  declare module.exports: $Exports<'restify/lib/errors/index'>;
}
declare module 'restify/lib/errors/rest_error.js' {
  declare module.exports: $Exports<'restify/lib/errors/rest_error'>;
}
declare module 'restify/lib/formatters/binary.js' {
  declare module.exports: $Exports<'restify/lib/formatters/binary'>;
}
declare module 'restify/lib/formatters/index.js' {
  declare module.exports: $Exports<'restify/lib/formatters/index'>;
}
declare module 'restify/lib/formatters/json.js' {
  declare module.exports: $Exports<'restify/lib/formatters/json'>;
}
declare module 'restify/lib/formatters/jsonp.js' {
  declare module.exports: $Exports<'restify/lib/formatters/jsonp'>;
}
declare module 'restify/lib/formatters/text.js' {
  declare module.exports: $Exports<'restify/lib/formatters/text'>;
}
declare module 'restify/lib/http_date.js' {
  declare module.exports: $Exports<'restify/lib/http_date'>;
}
declare module 'restify/lib/index.js' {
  declare module.exports: $Exports<'restify/lib/index'>;
}
declare module 'restify/lib/plugins/accept.js' {
  declare module.exports: $Exports<'restify/lib/plugins/accept'>;
}
declare module 'restify/lib/plugins/audit.js' {
  declare module.exports: $Exports<'restify/lib/plugins/audit'>;
}
declare module 'restify/lib/plugins/authorization.js' {
  declare module.exports: $Exports<'restify/lib/plugins/authorization'>;
}
declare module 'restify/lib/plugins/body_parser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/body_parser'>;
}
declare module 'restify/lib/plugins/body_reader.js' {
  declare module.exports: $Exports<'restify/lib/plugins/body_reader'>;
}
declare module 'restify/lib/plugins/bunyan.js' {
  declare module.exports: $Exports<'restify/lib/plugins/bunyan'>;
}
declare module 'restify/lib/plugins/conditional_request.js' {
  declare module.exports: $Exports<'restify/lib/plugins/conditional_request'>;
}
declare module 'restify/lib/plugins/cors.js' {
  declare module.exports: $Exports<'restify/lib/plugins/cors'>;
}
declare module 'restify/lib/plugins/date.js' {
  declare module.exports: $Exports<'restify/lib/plugins/date'>;
}
declare module 'restify/lib/plugins/fielded_text_body_parser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/fielded_text_body_parser'>;
}
declare module 'restify/lib/plugins/form_body_parser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/form_body_parser'>;
}
declare module 'restify/lib/plugins/full_response.js' {
  declare module.exports: $Exports<'restify/lib/plugins/full_response'>;
}
declare module 'restify/lib/plugins/gzip.js' {
  declare module.exports: $Exports<'restify/lib/plugins/gzip'>;
}
declare module 'restify/lib/plugins/index.js' {
  declare module.exports: $Exports<'restify/lib/plugins/index'>;
}
declare module 'restify/lib/plugins/json_body_parser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/json_body_parser'>;
}
declare module 'restify/lib/plugins/jsonp.js' {
  declare module.exports: $Exports<'restify/lib/plugins/jsonp'>;
}
declare module 'restify/lib/plugins/multipart_body_parser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/multipart_body_parser'>;
}
declare module 'restify/lib/plugins/pre/pause.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/pause'>;
}
declare module 'restify/lib/plugins/pre/pre_path.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/pre_path'>;
}
declare module 'restify/lib/plugins/pre/user_agent.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/user_agent'>;
}
declare module 'restify/lib/plugins/query.js' {
  declare module.exports: $Exports<'restify/lib/plugins/query'>;
}
declare module 'restify/lib/plugins/request_expiry.js' {
  declare module.exports: $Exports<'restify/lib/plugins/request_expiry'>;
}
declare module 'restify/lib/plugins/static.js' {
  declare module.exports: $Exports<'restify/lib/plugins/static'>;
}
declare module 'restify/lib/plugins/throttle.js' {
  declare module.exports: $Exports<'restify/lib/plugins/throttle'>;
}
declare module 'restify/lib/request.js' {
  declare module.exports: $Exports<'restify/lib/request'>;
}
declare module 'restify/lib/response.js' {
  declare module.exports: $Exports<'restify/lib/response'>;
}
declare module 'restify/lib/router.js' {
  declare module.exports: $Exports<'restify/lib/router'>;
}
declare module 'restify/lib/server.js' {
  declare module.exports: $Exports<'restify/lib/server'>;
}
declare module 'restify/lib/upgrade.js' {
  declare module.exports: $Exports<'restify/lib/upgrade'>;
}
declare module 'restify/lib/utils.js' {
  declare module.exports: $Exports<'restify/lib/utils'>;
}
