// flow-typed signature: 2a415b316e371f448d9cb0b85542d703
// flow-typed version: <<STUB>>/useragent_v2.2.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'useragent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'useragent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'useragent/bin/testfiles' {
  declare module.exports: any;
}

declare module 'useragent/bin/update' {
  declare module.exports: any;
}

declare module 'useragent/features/index' {
  declare module.exports: any;
}

declare module 'useragent/lib/regexps' {
  declare module.exports: any;
}

declare module 'useragent/lib/update' {
  declare module.exports: any;
}

// Filename aliases
declare module 'useragent/bin/testfiles.js' {
  declare module.exports: $Exports<'useragent/bin/testfiles'>;
}
declare module 'useragent/bin/update.js' {
  declare module.exports: $Exports<'useragent/bin/update'>;
}
declare module 'useragent/features/index.js' {
  declare module.exports: $Exports<'useragent/features/index'>;
}
declare module 'useragent/index' {
  declare module.exports: $Exports<'useragent'>;
}
declare module 'useragent/index.js' {
  declare module.exports: $Exports<'useragent'>;
}
declare module 'useragent/lib/regexps.js' {
  declare module.exports: $Exports<'useragent/lib/regexps'>;
}
declare module 'useragent/lib/update.js' {
  declare module.exports: $Exports<'useragent/lib/update'>;
}
