// flow-typed signature: a208caa4fc4b34d8852abf7560c5b843
// flow-typed version: <<STUB>>/uuid-1345_v^0.99.6/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid-1345'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid-1345' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid-1345/benchmark/index' {
  declare module.exports: any;
}

declare module 'uuid-1345/examples/example1' {
  declare module.exports: any;
}

declare module 'uuid-1345/examples/example2' {
  declare module.exports: any;
}

declare module 'uuid-1345/examples/example3' {
  declare module.exports: any;
}

declare module 'uuid-1345/gulpfile' {
  declare module.exports: any;
}

declare module 'uuid-1345/test/util' {
  declare module.exports: any;
}

declare module 'uuid-1345/test/UUID' {
  declare module.exports: any;
}

declare module 'uuid-1345/test/v1' {
  declare module.exports: any;
}

declare module 'uuid-1345/test/v3' {
  declare module.exports: any;
}

declare module 'uuid-1345/test/v4' {
  declare module.exports: any;
}

declare module 'uuid-1345/test/v5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid-1345/benchmark/index.js' {
  declare module.exports: $Exports<'uuid-1345/benchmark/index'>;
}
declare module 'uuid-1345/examples/example1.js' {
  declare module.exports: $Exports<'uuid-1345/examples/example1'>;
}
declare module 'uuid-1345/examples/example2.js' {
  declare module.exports: $Exports<'uuid-1345/examples/example2'>;
}
declare module 'uuid-1345/examples/example3.js' {
  declare module.exports: $Exports<'uuid-1345/examples/example3'>;
}
declare module 'uuid-1345/gulpfile.js' {
  declare module.exports: $Exports<'uuid-1345/gulpfile'>;
}
declare module 'uuid-1345/index' {
  declare module.exports: $Exports<'uuid-1345'>;
}
declare module 'uuid-1345/index.js' {
  declare module.exports: $Exports<'uuid-1345'>;
}
declare module 'uuid-1345/test/util.js' {
  declare module.exports: $Exports<'uuid-1345/test/util'>;
}
declare module 'uuid-1345/test/UUID.js' {
  declare module.exports: $Exports<'uuid-1345/test/UUID'>;
}
declare module 'uuid-1345/test/v1.js' {
  declare module.exports: $Exports<'uuid-1345/test/v1'>;
}
declare module 'uuid-1345/test/v3.js' {
  declare module.exports: $Exports<'uuid-1345/test/v3'>;
}
declare module 'uuid-1345/test/v4.js' {
  declare module.exports: $Exports<'uuid-1345/test/v4'>;
}
declare module 'uuid-1345/test/v5.js' {
  declare module.exports: $Exports<'uuid-1345/test/v5'>;
}
