// flow-typed signature: 08c0d7b4f1400633825a77b317802bf1
// flow-typed version: <<STUB>>/uuid-1345_v^0.99.6/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid-1345'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid-1345' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid-1345/benchmark/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid-1345/benchmark/index.js' {
  declare module.exports: $Exports<'uuid-1345/benchmark/index'>;
}
declare module 'uuid-1345/index' {
  declare module.exports: $Exports<'uuid-1345'>;
}
declare module 'uuid-1345/index.js' {
  declare module.exports: $Exports<'uuid-1345'>;
}
