// flow-typed signature: b6509cf0edced274d60fdcd5873de08f
// flow-typed version: <<STUB>>/@briskhome/core.log_vfile:src/core.log/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@briskhome/core.log/models/log.model' {
  declare module.exports: any;
}

declare module '@briskhome/core.log/specs/index.spec' {
  declare module.exports: any;
}

declare module '@briskhome/core.log/streams/bunyan-telegram' {
  declare module.exports: any;
}

// Filename aliases
declare module '@briskhome/core.log/index' {
  declare module.exports: $Exports<'@briskhome/core.log'>;
}
declare module '@briskhome/core.log/index.js' {
  declare module.exports: $Exports<'@briskhome/core.log'>;
}
declare module '@briskhome/core.log/models/log.model.js' {
  declare module.exports: $Exports<'@briskhome/core.log/models/log.model'>;
}
declare module '@briskhome/core.log/specs/index.spec.js' {
  declare module.exports: $Exports<'@briskhome/core.log/specs/index.spec'>;
}
declare module '@briskhome/core.log/streams/bunyan-telegram.js' {
  declare module.exports: $Exports<'@briskhome/core.log/streams/bunyan-telegram'>;
}
