// flow-typed signature: 23aead063649f69b7681184186d6f52b
// flow-typed version: <<STUB>>/@briskhome/core.notifications_vfile:src/core.notifications/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@briskhome/core.notifications/constants' {
  declare module.exports: any;
}

declare module '@briskhome/core.notifications/models/EventModel' {
  declare module.exports: any;
}

declare module '@briskhome/core.notifications/providers/telegram' {
  declare module.exports: any;
}

declare module '@briskhome/core.notifications/specs/index.spec' {
  declare module.exports: any;
}

declare module '@briskhome/core.notifications/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@briskhome/core.notifications/constants.js' {
  declare module.exports: $Exports<'@briskhome/core.notifications/constants'>;
}
declare module '@briskhome/core.notifications/index' {
  declare module.exports: $Exports<'@briskhome/core.notifications'>;
}
declare module '@briskhome/core.notifications/index.js' {
  declare module.exports: $Exports<'@briskhome/core.notifications'>;
}
declare module '@briskhome/core.notifications/models/EventModel.js' {
  declare module.exports: $Exports<'@briskhome/core.notifications/models/EventModel'>;
}
declare module '@briskhome/core.notifications/providers/telegram.js' {
  declare module.exports: $Exports<'@briskhome/core.notifications/providers/telegram'>;
}
declare module '@briskhome/core.notifications/specs/index.spec.js' {
  declare module.exports: $Exports<'@briskhome/core.notifications/specs/index.spec'>;
}
declare module '@briskhome/core.notifications/types.js' {
  declare module.exports: $Exports<'@briskhome/core.notifications/types'>;
}
