// flow-typed signature: 7e018edc0eeadb56b344ce4527f43d88
// flow-typed version: <<STUB>>/@briskhome/core.planner_vfile:src/core.planner/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.planner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.planner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@briskhome/core.planner/index' {
  declare module.exports: $Exports<'@briskhome/core.planner'>;
}
declare module '@briskhome/core.planner/index.js' {
  declare module.exports: $Exports<'@briskhome/core.planner'>;
}
