// flow-typed signature: ef66b18674cbe66f354cc5ab4cbe4e5e
// flow-typed version: <<STUB>>/@briskhome/core.config_vfile:src/core.config/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@briskhome/core.config/specs/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@briskhome/core.config/index' {
  declare module.exports: $Exports<'@briskhome/core.config'>;
}
declare module '@briskhome/core.config/index.js' {
  declare module.exports: $Exports<'@briskhome/core.config'>;
}
declare module '@briskhome/core.config/specs/index.spec.js' {
  declare module.exports: $Exports<'@briskhome/core.config/specs/index.spec'>;
}
