// flow-typed signature: 9a25a648b3f4b0ace1d7dbd289bb893d
// flow-typed version: <<STUB>>/@briskhome/core.db_vfile:src/core.db/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.db' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@briskhome/core.db/models/DeviceModel' {
  declare module.exports: any;
}

declare module '@briskhome/core.db/models/LocationModel' {
  declare module.exports: any;
}

declare module '@briskhome/core.db/models/ReadingModel' {
  declare module.exports: any;
}

declare module '@briskhome/core.db/models/SensorModel' {
  declare module.exports: any;
}

declare module '@briskhome/core.db/models/UserModel' {
  declare module.exports: any;
}

declare module '@briskhome/core.db/specs/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@briskhome/core.db/index' {
  declare module.exports: $Exports<'@briskhome/core.db'>;
}
declare module '@briskhome/core.db/index.js' {
  declare module.exports: $Exports<'@briskhome/core.db'>;
}
declare module '@briskhome/core.db/models/DeviceModel.js' {
  declare module.exports: $Exports<'@briskhome/core.db/models/DeviceModel'>;
}
declare module '@briskhome/core.db/models/LocationModel.js' {
  declare module.exports: $Exports<'@briskhome/core.db/models/LocationModel'>;
}
declare module '@briskhome/core.db/models/ReadingModel.js' {
  declare module.exports: $Exports<'@briskhome/core.db/models/ReadingModel'>;
}
declare module '@briskhome/core.db/models/SensorModel.js' {
  declare module.exports: $Exports<'@briskhome/core.db/models/SensorModel'>;
}
declare module '@briskhome/core.db/models/UserModel.js' {
  declare module.exports: $Exports<'@briskhome/core.db/models/UserModel'>;
}
declare module '@briskhome/core.db/specs/index.spec.js' {
  declare module.exports: $Exports<'@briskhome/core.db/specs/index.spec'>;
}
