// flow-typed signature: 031634002f5310550e04170b00cf1f6c
// flow-typed version: <<STUB>>/@briskhome/core.pki_vfile:src/core.pki/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.pki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.pki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@briskhome/core.pki/specs/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@briskhome/core.pki/index' {
  declare module.exports: $Exports<'@briskhome/core.pki'>;
}
declare module '@briskhome/core.pki/index.js' {
  declare module.exports: $Exports<'@briskhome/core.pki'>;
}
declare module '@briskhome/core.pki/specs/index.spec.js' {
  declare module.exports: $Exports<'@briskhome/core.pki/specs/index.spec'>;
}
