// flow-typed signature: e118e1cff6c864249da7e28b022dd951
// flow-typed version: <<STUB>>/@briskhome/core.bus_vfile:src/core.bus/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@briskhome/core.bus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@briskhome/core.bus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@briskhome/core.bus/specs/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@briskhome/core.bus/index' {
  declare module.exports: $Exports<'@briskhome/core.bus'>;
}
declare module '@briskhome/core.bus/index.js' {
  declare module.exports: $Exports<'@briskhome/core.bus'>;
}
declare module '@briskhome/core.bus/specs/index.spec.js' {
  declare module.exports: $Exports<'@briskhome/core.bus/specs/index.spec'>;
}
